import { random, shuffle } from '../../core/random';
export interface Entry {w:string;g:string;p?:string}
export interface Slot {id:number;direction:'across'|'down';cells:number[];number:number;word:string;clue:string}
export interface Puzzle {size:number;mask:boolean[];solution:string[];slots:Slot[];seed:number;nodes:number}
export function normalizeAnswer(s:string){return s.toLowerCase().normalize('NFD').replace(/n\u0303/g,'ñ').replace(/[\u0300-\u036f]/g,'').normalize('NFC');}
export function prepareEntries(raw:Entry[]){const byWord=new Map<string,Entry>();for(const e of raw){const w=normalizeAnswer(e.w);if(!e.g||!/^[a-zñ]{3,13}$/.test(w)||normalizeAnswer(e.g).split(/[^a-zñ]+/).includes(w))continue;const old=byWord.get(w);if(!old||(e.p==='noun'&&old.p!=='noun')||(e.p===old.p&&e.g.length<old.g.length))byWord.set(w,{w,g:e.g,p:e.p});}return [...byWord.values()];}
type EmptySlot=Omit<Slot,'word'|'clue'>;
export function scanSlots(mask:boolean[],size:number):EmptySlot[]{const slots:EmptySlot[]=[];let number=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=y*size+x;if(!mask[i])continue;const across=x===0||!mask[i-1],down=y===0||!mask[i-size];if(!across&&!down)continue;number++;for(const direction of ['across','down'] as const){if(direction==='across'&&!across||direction==='down'&&!down)continue;const cells:number[]=[];let xx=x,yy=y;while(xx<size&&yy<size&&mask[yy*size+xx]){cells.push(yy*size+xx);if(direction==='across')xx++;else yy++;}slots.push({id:slots.length,direction,cells,number});}}return slots;}
export function validMask(mask:boolean[],size:number){const slots=scanSlots(mask,size);if(slots.some(s=>s.cells.length<3))return false;const start=mask.indexOf(true);if(start<0)return false;const seen=new Set<number>([start]),queue=[start];for(let i=0;i<queue.length;i++){const p=queue[i],x=p%size,y=Math.floor(p/size);for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,n=b*size+a;if(a>=0&&a<size&&b>=0&&b<size&&mask[n]&&!seen.has(n)){seen.add(n);queue.push(n);}}}return seen.size===mask.filter(Boolean).length;}
export function template(size:number,seed:number){let mask=Array(size*size).fill(true);const order=shuffle(Array.from({length:Math.ceil(size*size/2)},(_,i)=>i),seed);for(const i of order.items){const j=size*size-1-i,tryMask=mask.slice();tryMask[i]=false;tryMask[j]=false;if(validMask(tryMask,size)&&tryMask.filter(Boolean).length>=size*size*.68)mask=tryMask;}return mask;}
interface Index {length:Map<number,Entry[]>;positions:Map<string,Entry[]>}
function buildIndex(entries:Entry[],size:number):Index {const length=new Map<number,Entry[]>(),positions=new Map<string,Entry[]>();for(const e of entries){if(e.w.length<3||e.w.length>size)continue;const a=length.get(e.w.length)||[];a.push(e);length.set(e.w.length,a);for(let i=0;i<e.w.length;i++){const key=`${e.w.length}:${i}:${e.w[i]}`,p=positions.get(key)||[];p.push(e);positions.set(key,p);}}return{length,positions};}
export function solveMask(mask:boolean[],size:number,entries:Entry[],seed:number,maxNodes=2000,givenIndex?:Index):Puzzle|null {
 const slots=scanSlots(mask,size);if(!validMask(mask,size))return null;const index=givenIndex||buildIndex(entries,size),grid=Array(size*size).fill(''),filled=new Map<number,Entry>(),used=new Set<string>();let nodes=0;const cache=new Map<string,Entry[]>();
 function candidates(slot:EmptySlot){const pattern=slot.cells.map(i=>grid[i]||'.').join(''),key=`${slot.cells.length}:${pattern}`;let a=cache.get(key);if(!a){a=index.length.get(slot.cells.length)||[];for(let i=0;i<pattern.length;i++)if(pattern[i]!=='.'){const p=index.positions.get(`${pattern.length}:${i}:${pattern[i]}`)||[];if(p.length<a.length)a=p;}a=a.filter(e=>[...pattern].every((ch,i)=>ch==='.'||e.w[i]===ch));cache.set(key,a);}return a;}
 function search():boolean{if(filled.size===slots.length)return true;if(++nodes>maxNodes)return false;let chosen:EmptySlot|undefined,choices:Entry[]=[];for(const slot of slots){if(filled.has(slot.id))continue;const a=candidates(slot);if(!a.length||a.every(e=>used.has(e.w)))return false;if(!chosen||a.length<choices.length){chosen=slot;choices=a;if(a.length===1)break;}}if(!chosen)return false;choices=choices.filter(e=>!used.has(e.w));
   // Least-constraining values favour letters with many potential crossing words.
   // Seeded jitter keeps successive puzzles varied without relying on wall-clock time.
   let choiceSeed=seed^nodes*0x9e3779b9;const ordered=choices.map(e=>{const [jitter,next]=random(choiceSeed);choiceSeed=next;let score=jitter*3+(e.p==='noun'?.3:0);for(let n=0;n<chosen!.cells.length;n++){const cell=chosen!.cells[n];if(grid[cell])continue;const crossing=slots.find(slot=>slot.id!==chosen!.id&&slot.cells.includes(cell));if(crossing&&!filled.has(crossing.id)){const count=index.positions.get(`${crossing.cells.length}:${crossing.cells.indexOf(cell)}:${e.w[n]}`)?.length||0;if(!count)return{e,score:-Infinity};score+=Math.log2(count);}}return{e,score};}).filter(v=>Number.isFinite(v.score)).sort((a,b)=>b.score-a.score);
   for(const {e} of ordered){if(nodes>maxNodes)return false;const changes=chosen.cells.filter(i=>!grid[i]);chosen.cells.forEach((i,n)=>grid[i]=e.w[n]);used.add(e.w);filled.set(chosen.id,e);if(search())return true;used.delete(e.w);filled.delete(chosen.id);for(const i of changes)grid[i]='';}return false;
 }
 return search()?{size,mask,solution:grid,slots:slots.map(s=>({...s,word:filled.get(s.id)!.w,clue:filled.get(s.id)!.g})),seed,nodes}:null;
}
export function generate(size:number,entries:Entry[],seed:number,maxAttempts=12):Puzzle|null {
 const index=buildIndex(entries,size);
 function attempt(initial:number,count:number){let rng=initial;const masks:{mask:boolean[];seed:number;cost:number}[]=[];for(let i=0;i<count;i++){const [,next]=random(rng);rng=next;const mask=template(size,rng),slots=scanSlots(mask,size);const cost=slots.reduce((sum,s)=>sum+Math.max(0,s.cells.length-6)**3,0);masks.push({mask,seed:rng,cost});}masks.sort((a,b)=>a.cost-b.cost);for(const m of masks){const puzzle=solveMask(m.mask,size,entries,m.seed,2000,index);if(puzzle)return puzzle;}return null;}
 // A corpus-verified template family bounds pathological random-template searches.
 // A rare fallback may repeat a puzzle; it still has fully validated crossing entries.
 return attempt(seed,maxAttempts)||(seed!==78233?attempt(78233,12):null);
}
