import { useState } from 'react';
import { type Square } from 'chess.js';
import { labels,select,difficulty,tr,type GameDefinition,type GameViewProps } from '../../core/types';
import { engineMove } from '../../core/stockfish';
import { canClaimDraw,chessReducer,claimableMoves,createChess,loadChess,migrateChess,type ChessState } from './engine';
export { chessReducer } from './engine';
const glyphs:Record<string,string>={wk:'♔',wq:'♕',wr:'♖',wb:'♗',wn:'♘',wp:'♙',bk:'♚',bq:'♛',br:'♜',bb:'♝',bn:'♞',bp:'♟'};
const pieceNames:Record<string,{es:string;en:string}>={k:labels('rey','king'),q:labels('dama','queen'),r:labels('torre','rook'),b:labels('alfil','bishop'),n:labels('caballo','knight'),p:labels('peón','pawn')};
function View({state:s,dispatch,locale:l,paused}:GameViewProps<ChessState>){
 const c=loadChess(s),[flip,setFlip]=useState(false),[intended,setIntended]=useState(''),squares=c.board().flat(),board=flip?[...squares].reverse():squares;
 const candidates=s.selected?c.moves({square:s.selected as Square,verbose:true}).map(m=>m.to):[],claimMoves=claimableMoves(s),locked=paused||s.status!=='playing'||!!s.drawOffer;
 return <div className="chess-layout"><div><p className="game-message">{s.winner?tr(l,s.winner==='w'?'Ganan las blancas':'Ganan las negras',s.winner==='w'?'White wins':'Black wins'):s.status==='draw'?tr(l,'Tablas','Draw'):tr(l,c.turn()==='w'?'Turno de blancas':'Turno de negras',c.turn()==='w'?'White to move':'Black to move')}</p>
 <div className="chess-board" role="group" aria-label={tr(l,'Tablero de ajedrez','Chess board')}>{board.map((piece,i)=>{const n=flip?63-i:i,square=String.fromCharCode(97+n%8)+(8-Math.floor(n/8));return <button key={square} className={'chess-cell '+((Math.floor(n/8)+n%8)%2?'dark':'light')+(s.selected===square?' selected':'')+(s.lastMove.includes(square)?' last':'')} onClick={()=>dispatch({type:'SELECT',square})} disabled={locked||!!s.promotion} aria-label={`${square} ${piece?`${piece.color==='w'?tr(l,'blancas','white'):tr(l,'negras','black')} ${pieceNames[piece.type][l]}`:tr(l,'vacía','empty')}`}><span className={'chess-piece '+(piece?.color==='w'?'white':'black')}>{piece?glyphs[piece.color+piece.type]:''}</span>{candidates.includes(square as Square)?<span className="move-dot"/>:null}<small>{square}</small></button>;})}</div>
 {s.promotion?<div className="controls" role="group" aria-label={tr(l,'Elige promoción','Choose promotion')}>{['q','r','b','n'].map(p=><button key={p} disabled={locked} onClick={()=>dispatch({type:'PROMOTE',promotion:p})} aria-label={pieceNames[p][l]}>{glyphs[c.turn()+p]} {pieceNames[p][l]}</button>)}<button disabled={locked} onClick={()=>dispatch({type:'CANCEL_PROMOTION'})}>{tr(l,'Cancelar','Cancel')}</button></div>:null}
 {s.drawOffer?<div className="notice"><p>{tr(l,s.drawOffer==='w'?'Blancas ofrecen tablas. Negras deciden.':'Negras ofrecen tablas. Blancas deciden.',s.drawOffer==='w'?'White offers a draw. Black decides.':'Black offers a draw. White decides.')}</p><div className="controls"><button disabled={paused} onClick={()=>dispatch({type:'ACCEPT_DRAW'})}>{tr(l,'Aceptar tablas','Accept draw')}</button><button disabled={paused} onClick={()=>dispatch({type:'DECLINE_DRAW'})}>{tr(l,'Rechazar','Decline')}</button></div></div>:null}
 <div className="controls"><button onClick={()=>setFlip(!flip)}>{tr(l,'Girar tablero','Flip board')}</button><button disabled={locked||!canClaimDraw(s)} onClick={()=>dispatch({type:'CLAIM'})}>{tr(l,'Reclamar tablas','Claim draw')}</button><button disabled={locked} onClick={()=>dispatch({type:'OFFER_DRAW'})}>{tr(l,'Ofrecer tablas','Offer draw')}</button><button disabled={locked} onClick={()=>dispatch({type:'RESIGN'})}>{tr(l,'Abandonar','Resign')}</button></div>
 {claimMoves.length>0&&<div className="controls"><label>{tr(l,'Jugada que permite reclamar tablas','Intended move allowing a draw claim')}<select disabled={locked} value={claimMoves.includes(intended)?intended:''} onChange={e=>setIntended(e.target.value)}><option value="">{tr(l,'Elige jugada','Choose move')}</option>{claimMoves.map(san=><option key={san}>{san}</option>)}</select></label><button disabled={locked||!claimMoves.includes(intended)} onClick={()=>dispatch({type:'CLAIM',san:intended})}>{tr(l,'Anunciar y reclamar','Declare and claim')}</button></div>}
 </div><ol className="move-log">{s.log.map((v,i)=><li key={i}>{v}</li>)}</ol></div>;
}
export const chess:GameDefinition<ChessState>={id:'chess',name:labels('Ajedrez','Chess'),description:labels('Piensa tu próximo movimiento.','Think a move ahead.'),category:'board',icon:'♔',version:2,defaults:{humans:1,difficulty:'medium'},options:[select('humans','Jugadores humanos','Human players',[[1,'Contra Stockfish','Against Stockfish'],[2,'Dos personas','Two people']],1),{...difficulty,visibleWhen:c=>Number(c.humans)<2}],create:(cfg,seed)=>createChess(cfg,seed),reducer:chessReducer,View,
 getTurn:(s,cfg)=>{if(s.status!=='playing')return null;const color=s.drawOffer?(s.drawOffer==='w'?'b':'w'):loadChess(s).turn();return {player:color==='w'?0:1,bot:Number(cfg.humans)===1&&color==='b',hidden:false};},
 bot:async(s,cfg)=>{if(s.status!=='playing')return null;if(s.drawOffer)return {type:'DECLINE_DRAW'};if(canClaimDraw(s))return {type:'CLAIM'};const m=await engineMove(s.fen,String(cfg.difficulty));return {type:'MOVE',from:m.slice(0,2),to:m.slice(2,4),promotion:m[4]};},
 guide:[{title:labels('El objetivo','The goal'),text:labels('Da jaque mate: ataca al rey y elimina todas sus salidas legales. Nunca se captura un rey. Juegas con blancas contra Stockfish; en local, jugadores 1 y 2 llevan blancas y negras. No hay reloj de ajedrez ni derrota por tiempo.','Checkmate the king: attack it with no legal escape. Kings are never captured. You play White against Stockfish; locally, players 1 and 2 play White and Black. There is no chess clock or timeout loss.'),diagram:'♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜\n♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟\n· · · · · · · ·\n♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙\n♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖'},
 {title:labels('Mueve una pieza','Move a piece'),text:labels('Pulsa tu peón de e2 y después e4. Los puntos señalan destinos legales.','Tap the e2 pawn, then e4. Dots show legal destinations.'),action:{type:'MOVE',from:'e2',to:'e4'}},
 {title:labels('Enroque, al paso y promoción','Castling, en passant and promotion'),text:labels('Enroca solo si rey y torre no se han movido, el rey no está en jaque y no atraviesa ni termina en casillas atacadas. La captura al paso solo está disponible inmediatamente después del avance doble rival. En la última fila elige dama, torre, alfil o caballo.','Castle only if king and rook have not moved, the king is not in check, and it neither crosses nor lands on an attacked square. En passant is available only immediately after an opponent’s double pawn push. Choose queen, rook, bishop or knight on promotion.'),diagram:'e1 + h1 → rey g1, torre f1\npeón e5 + rival d7–d5 → e5×d6'},
 {title:labels('Tablas y reclamaciones','Draws and claims'),text:labels('Ahogado y material insuficiente terminan automáticamente. Tres posiciones idénticas o 50 movimientos por bando sin captura ni avance de peón permiten reclamar ahora o anunciando una jugada legal que cumpla la condición. Repetición respeta turno, enroque y capturas al paso legales. Cinco repeticiones o 75 movimientos terminan automáticamente; el mate tiene prioridad. Las tablas por acuerdo requieren aceptar la oferta rival.','Stalemate and insufficient material end automatically. Three identical positions or 50 moves per side without captures or pawn moves allow a claim now or by declaring a qualifying legal move. Repetition includes turn, castling rights and legal en passant. Five repetitions or 75 moves end automatically; checkmate has priority. Agreed draws require accepting the opponent’s offer.')},],
 summarize:s=>({moves:s.moves,result:s.status==='draw'?'½-½':s.winner==='w'?'1-0':s.winner==='b'?'0-1':'*',winner:s.winner==='w'?'white':s.winner==='b'?'black':'none',reason:s.endReason??'playing'}),migrate:migrateChess};
