import { PixelSprite } from "../../ui/PixelSprite";
import type { Sprite } from "../../ui/pixel-art";
const pieces: Record<string, Sprite> = {
  p: [
    "................",
    "......kkkk......",
    ".....khbbbk.....",
    "....khbbbbsk....",
    "....khbbbbsk....",
    ".....kbbssk.....",
    "......kkkk......",
    "......kbbk......",
    ".....khbbsk.....",
    ".....khbbsk.....",
    ".....khbbsk.....",
    "....khbbbssk....",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  r: [
    "................",
    "..kkk.kkkk.kkk..",
    "..kbk.kbbk.kbk..",
    "..kbkkkbbkkkbk..",
    "..khbbbbbbbbsk..",
    "...kbbbbbbbsk...",
    "...kkkkkkkkkk...",
    "....khbbbssk....",
    "....khbbbssk....",
    "....khbbbssk....",
    "....khbbbssk....",
    "...khbbbbbssk...",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  b: [
    ".......kk.......",
    "......kbbk......",
    ".....khbssk.....",
    "....khbbsbsk....",
    "....khbsbbbsk...",
    "....khbsbbbsk...",
    ".....kbbbssk....",
    "......kkkk......",
    ".....khbbsk.....",
    "......kbbk......",
    ".....khbbsk.....",
    "....khbbbssk....",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  n: [
    "....kk..kk......",
    "....kbkkbbk.....",
    "....khbbbbsk....",
    "...khbkbbbssk...",
    "..khbbbbbbbssk..",
    ".khbbbbbbbbssk..",
    ".kbbbbkkbbbssk..",
    ".ksskk.khbbssk..",
    "..kk..khbbbssk..",
    ".....khbbbbssk..",
    "....khbbbbsssk..",
    "...khbbbbssssk..",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  q: [
    "..kk...kk...kk..",
    "..kk...kk...kk..",
    "..kbk.kbbk.kbk..",
    "..kbkkhbbkkbsk..",
    "...kbbbbbbbsk...",
    "...khbbbbbbsk...",
    "....kbbbbssk....",
    "....kkkkkkkk....",
    ".....khbbsk.....",
    ".....khbbsk.....",
    ".....khbbsk.....",
    "....khbbbssk....",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  k: [
    ".......kk.......",
    "......kbbk......",
    ".....kbbbbk.....",
    "......kbbk......",
    "....kkkkkkkk....",
    "...khbbbbbbsk...",
    "...khbbbbbbsk...",
    "....kbbbbssk....",
    ".....khbbsk.....",
    ".....khbbsk.....",
    ".....khbbsk.....",
    "....khbbbssk....",
    "...khbbbbbssk...",
    "...kkkkkkkkkk...",
    "..khbbbbbbbbsk..",
    "..kssssssssssk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
};
export function ChessPiece({ type, color }: { type: string; color: string }) {
  return (
    <PixelSprite
      className="chess-sprite"
      sprite={pieces[type]}
      palette={
        color === "w"
          ? {
              k: "#26303b",
              b: "var(--card-face, #f8f2df)",
              h: "#fffdf2",
              s: "#bfb8a7",
            }
          : { k: "#101d2b", b: "#3c5165", h: "#829cad", s: "#263648" }
      }
    />
  );
}
