import { describe, expect, it } from 'vitest';
import { arcadeReducer, createArcade } from '../src/games/arcade/engines';
import { blocksReducer, cells, createBlocks, drawPiece, ghostY, lockPiece, nesAdvance, nesGravity, PIECES, rotate, valid, type BlocksState } from '../src/games/arcade/blocks';
const config={profile:'modern',mode:'infinite',level:0,target:40,time:120};
function advance(s:BlocksState,seconds:number,hz:number,c=config){for(let i=0;i<Math.round(seconds*hz);i++)s=blocksReducer(s,{type:'TICK',dt:1/hz},c);return s;}
describe('Arcade deterministic engines',()=>{
 it('swipes choose the dominant direction, reject reversals and release pointer state',()=>{let s=createArcade('snake',{},1);s=arcadeReducer(s,{type:'POINTER',x:360,y:220},{});s=arcadeReducer(s,{type:'POINTER_MOVE',x:360,y:170,down:true},{});expect(s.queued).toEqual([0,-1]);s=arcadeReducer(s,{type:'TICK',dt:.13},{});s=arcadeReducer(s,{type:'POINTER_MOVE',x:360,y:250,down:true},{});expect(s.queued).toEqual([0,-1]);s=arcadeReducer(s,{type:'RELEASE'},{});expect(s.pointer).toBeUndefined();});
 it('feedback is saved with the event and expires by simulation time',()=>{let s=createArcade('snake',{},1);s.food=[9,10];s=arcadeReducer(s,{type:'TICK',dt:.13},{});expect(s.effect).toMatchObject({type:'eat',value:10});const restored=JSON.parse(JSON.stringify(s));expect(arcadeReducer(restored,{type:'TICK',dt:.4},{}).effect).toBeUndefined();let runner=createArcade('runner',{},1);runner.elapsed=9.99;runner.score=99;runner=arcadeReducer(runner,{type:'TICK',dt:.02},{});expect(runner.effect?.type).toBe('milestone');});
 it.each(['snake','runner','flappy','breakout'])('%s agrees across display frequencies and survives JSON serialization',kind=>{let a=createArcade(kind,{},234),b=createArcade(kind,{},234);for(let i=0;i<60;i++)a=arcadeReducer(a,{type:'TICK',dt:1/60},{});for(let i=0;i<144;i++)b=arcadeReducer(b,{type:'TICK',dt:1/144},{});expect({...a,accumulator:0}).toEqual({...b,accumulator:0});expect(JSON.parse(JSON.stringify(a))).toEqual(a);});
 it('rejects a snake reversal and allows entry into a vacated tail cell',()=>{let s=createArcade('snake',{},1);s=arcadeReducer(s,{type:'LEFT'},{});expect(s.queued).toEqual([1,0]);Object.assign(s,{snake:[[1,1],[1,2],[0,2],[0,1]],direction:[0,-1],queued:[-1,0],food:[19,19],period:1/120});s=arcadeReducer(s,{type:'TICK',dt:1/120},{});expect(s.status).toBe('playing');expect(s.snake[0]).toEqual([0,1]);});
 it('places food only on free cells and wins a full board',()=>{let s=createArcade('snake',{},1);Object.assign(s,{snake:Array.from({length:399},(_,i)=>[i%20,Math.floor(i/20)]),direction:[1,0],queued:[1,0],food:[19,19],period:1/120});s.snake=[ [18,19], ...s.snake.filter((p:number[])=>p[0]!==18||p[1]!==19) ];s=arcadeReducer(s,{type:'TICK',dt:1/120},{});expect(s.status).toBe('won');expect(s.score).toBe(10);});
 it('runner only jumps from the floor; a collision loses',()=>{let s=createArcade('runner',{},1);s=arcadeReducer(s,{type:'JUMP'},{});expect(s.vy).toBe(560);s=arcadeReducer(s,{type:'TICK',dt:.05},{});const v=s.vy;s=arcadeReducer(s,{type:'JUMP'},{});expect(s.vy).toBe(v);Object.assign(s,{y:0,vy:0,obstacles:[{x:100,w:40,h:40}]});expect(arcadeReducer(s,{type:'TICK',dt:1/120},{}).status).toBe('lost');});
 it('flap requires an input edge and passing a pipe scores once',()=>{let s=createArcade('flappy',{},1);s=arcadeReducer(s,{type:'JUMP',repeat:true},{});expect(s.vy).toBe(0);s=arcadeReducer(s,{type:'JUMP'},{});expect(s.vy).toBe(-285);Object.assign(s,{y:200,vy:0,pipes:[{x:89,gap:200,scored:false}]});s=arcadeReducer(s,{type:'TICK',dt:.1},{});expect(s.score).toBe(1);s=arcadeReducer(s,{type:'TICK',dt:.1},{});expect(s.score).toBe(1);});
 it('brick contact scores once and a lost ball consumes a life',()=>{let s=createArcade('breakout',{},1);Object.assign(s,{x:50,y:44,vx:0,vy:260});s=arcadeReducer(s,{type:'TICK',dt:1/120},{});expect(s.score).toBe(10);expect(s.vy).toBeLessThan(0);Object.assign(s,{y:449,vy:300,x:0});s=arcadeReducer(s,{type:'TICK',dt:.05},{});expect(s.lives).toBe(2);});
});
describe('Modern falling blocks',()=>{
 it('draws a permutation for every seven-piece bag',()=>{const s=createBlocks(config,123);s.queue=[];const draws=Array.from({length:70},()=>drawPiece(s));for(let i=0;i<70;i+=7)expect(draws.slice(i,i+7).sort()).toEqual([...PIECES].sort());});
 it.each(PIECES)('%s returns to its exact shape after four rotations',piece=>{const s=createBlocks(config,1);Object.assign(s,{piece,x:3,y:5,rotation:0});const before=cells(s);for(let i=0;i<4;i++)expect(rotate(s,1)).toBe(true);expect(cells(s)).toEqual(before);});
 it('SRS kicks a vertical I away from the left wall',()=>{const s=createBlocks(config,1);Object.assign(s,{piece:'I',x:-2,y:5,rotation:1});expect(valid(s)).toBe(true);expect(rotate(s,1)).toBe(true);expect(s.x).toBe(0);expect(valid(s)).toBe(true);});
 it('allows one hold per piece and hard drop locks immediately',()=>{let s=createBlocks(config,4);const first=s.piece;s=blocksReducer(s,{type:'HOLD'},config);s=advance(s,1/60,60);expect(s.hold).toBe(first);expect(s.held).toBe(true);const current=s.piece;s=blocksReducer(s,{type:'HOLD'},config);s=advance(s,1/60,60);expect(s.piece).toBe(current);s=blocksReducer(s,{type:'HARD'},config);s=advance(s,1/60,60);expect(s.moves).toBe(1);expect(s.held).toBe(false);expect(s.score).toBeGreaterThan(0);});
 it('scores four lines, back-to-back, combos and level transition',()=>{const s=createBlocks(config,3);const fill=()=>{s.board=Array.from({length:20},(_,y)=>Array.from({length:10},(_,x)=>y>=16&&x!==4?'J':null));Object.assign(s,{piece:'I',x:2,y:16,rotation:1,lastRotate:false});};fill();lockPiece(s,config);expect(s.score).toBe(800);expect(s.lines).toBe(4);fill();lockPiece(s,config);expect(s.score).toBe(2050);expect(s.lines).toBe(8);});
 it('recognizes a three-corner T-spin and does not award it without rotation',()=>{const s=createBlocks(config,3);Object.assign(s,{piece:'T',x:3,y:17,rotation:0,lastRotate:true});s.board[17][3]='J';s.board[17][5]='J';s.board[19][3]='J';lockPiece(s,config);expect(s.score).toBe(400);expect(s.message).toContain('T-spin');});
 it('locks after 30 grounded simulation frames',()=>{let s=createBlocks(config,1);s.y=ghostY(s);s=advance(s,29/60,60);expect(s.moves).toBe(0);s=advance(s,1/60,60);expect(s.moves).toBe(1);});
 it('has identical physics and DAS at 30, 60 and 144 Hz',()=>{let s=createBlocks(config,9);s=blocksReducer(s,{type:'LEFT',down:true},config);const states=[30,60,144].map(h=>advance(s,3,h));for(const a of states)expect({...a,accumulator:0}).toEqual({...states[0],accumulator:0});});
 it('ends time and lines modes at the selected target',()=>{const timed={...config,mode:'time',time:1};expect(advance(createBlocks(timed,2),1,60,timed).status).toBe('won');const s=createBlocks(config,2);s.lines=39;s.board[19]=Array(10).fill('J');s.board[19][4]=null;Object.assign(s,{piece:'I',rotation:1,x:2,y:16});lockPiece(s,{...config,mode:'lines'});expect(s.status).toBe('won');});
});
describe('Classic NTSC falling blocks',()=>{
 const c={...config,profile:'classic'};
 it('uses verified gravity values including level 29',()=>{expect([0,8,9,10,13,16,19,28,29].map(nesGravity)).toEqual([48,8,6,5,4,3,2,2,1]);});
 it('LFSR rotates both bytes and feeds back bit 1 XOR',()=>{expect(nesAdvance(0x8988)).toBe(0x4444);expect(nesAdvance(0x4444)).toBe(0x2222);expect(nesAdvance(0x0002)).toBe(0x0081);});
 it('is not a bag: droughts and repeats remain possible',()=>{const s=createBlocks(c,15);const drawn=[];for(let i=0;i<140;i++){s.nesSeed=nesAdvance(s.nesSeed);drawn.push(drawPiece(s));}expect(drawn.slice(0,7).length).toBe(7);expect(new Set(drawn.slice(0,7)).size).toBeLessThan(7);});
 it('rejects wall rotations instead of kicking',()=>{const s=createBlocks(c,2);Object.assign(s,{piece:'I',rotation:1,x:0,y:4});expect(valid(s)).toBe(true);expect(rotate(s,1)).toBe(false);expect(s.x).toBe(0);});
 it('has no reserve or hard drop',()=>{let s=createBlocks(c,2);const p=s.piece;s=blocksReducer(s,{type:'HOLD'},c);s=blocksReducer(s,{type:'HARD'},c);s=advance(s,1/60,60,c);expect(s.piece).toBe(p);expect(s.hold).toBeNull();expect(s.moves).toBe(0);});
 it('scores classic four-line clears and delays spawning',()=>{const s=createBlocks(c,2);s.board=Array.from({length:20},(_,y)=>Array.from({length:10},(_,x)=>y>=16&&x!==4?'J':null));Object.assign(s,{piece:'I',x:4,y:18,rotation:1});lockPiece(s,c);expect(s.lines).toBe(4);expect(s.score).toBe(1200);expect(s.delay).toBe(30);});
 it('uses 16-frame DAS and then six-frame repetition',()=>{let s=createBlocks(c,1);s=blocksReducer(s,{type:'LEFT',down:true},c);const frame=()=>{s=blocksReducer(s,{type:'TICK',dt:1/60.0988138974405},c);};frame();expect(s.x).toBe(4);for(let i=0;i<14;i++)frame();expect(s.x).toBe(4);frame();expect(s.x).toBe(3);for(let i=0;i<5;i++)frame();expect(s.x).toBe(3);frame();expect(s.x).toBe(2);});
 it('keeps the same sequence and frame timing across refresh rates and save/resume',()=>{const start=createBlocks(c,823);const a=advance(start,5,60,c),b=advance(JSON.parse(JSON.stringify(start)),5,144,c);expect({...a,accumulator:0}).toEqual({...b,accumulator:0});});
 it('clears held controls on resume',()=>{let s=createBlocks(c,1);s=blocksReducer(s,{type:'LEFT',down:true},c);s=blocksReducer(s,{type:'RELEASE'},c);expect(s.input).toEqual({left:false,right:false,down:false});expect(s.pending).toEqual([]);});
 it('retains fully charged DAS at a wall and moves immediately when space appears',()=>{let s=createBlocks(c,1);Object.assign(s,{piece:'I',rotation:1,x:0,y:5,das:15,horizontal:-1,input:{left:true,right:false,down:false}});s=blocksReducer(s,{type:'TICK',dt:1/60.0988138974405},c);expect(s.x).toBe(0);expect(s.das).toBe(16);s.x=5;s=blocksReducer(s,{type:'TICK',dt:1/60.0988138974405},c);expect(s.x).toBe(4);expect(s.das).toBe(10);});
 it('soft drop suppresses both lateral movement and DAS accumulation',()=>{let s=createBlocks(c,1);Object.assign(s,{piece:'T',x:5,y:5,das:8,horizontal:-1,input:{left:true,right:false,down:true}});s=advance(s,10/60.0988138974405,60.0988138974405,c);expect(s.x).toBe(5);expect(s.das).toBe(8);});
 it('resumes exactly from a serialized entry-delay state at another refresh rate',()=>{let s=createBlocks(c,7);Object.assign(s,{piece:'O',x:5,y:18,rotation:0,frame:41});lockPiece(s,c);expect(s.delay).toBe(10);const a=advance(s,1,60,c),b=advance(JSON.parse(JSON.stringify(s)),1,144,c);expect({...a,accumulator:0}).toEqual({...b,accumulator:0});});
});
