import { afterEach, describe, expect, it, vi } from 'vitest';
import { playSound, setSoundEnabled, soundForTransition, unlockAudio } from '../src/core/audio';
import { baseState, type Action } from '../src/core/types';
const state=(extra:Record<string,any>={})=>({...baseState(1),...extra});
const cue=(id:string,before:Record<string,any>,after:Record<string,any>,action:Action={type:'TICK'})=>soundForTransition(id,state(before),state(after),action);
describe('meaningful sound events',()=>{
 it('plays result cues once and keeps release/steady physics silent',()=>{expect(cue('snake',{}, {status:'lost'})).toBe('failure');expect(cue('crossword',{}, {status:'won'})).toBe('success');expect(cue('snake',{status:'lost'},{status:'lost'})).toBeNull();expect(cue('blocks',{y:2},{y:3})).toBeNull();expect(cue('runner',{score:12},{score:13})).toBeNull();expect(cue('flappy',{vy:0},{vy:2})).toBeNull();expect(cue('snake',{}, {score:10},{type:'RELEASE'})).toBeNull();});
 it('distinguishes a jump/flap input edge, food and occasional milestones',()=>{expect(cue('runner',{y:0,vy:0},{y:0,vy:560},{type:'JUMP'})).toBe('jump');expect(cue('runner',{y:10,vy:40},{y:10,vy:40},{type:'JUMP'})).toBeNull();expect(cue('runner',{score:99},{score:100})).toBe('coin');expect(cue('flappy',{vy:100},{vy:-285},{type:'POINTER'})).toBe('flap');expect(cue('snake',{score:0},{score:10})).toBe('eat');});
 it('detects bricks, life loss and line clears without sounding on gravity',()=>{expect(cue('breakout',{score:0},{score:10})).toBe('bounce');expect(cue('breakout',{lives:3},{lives:2})).toBe('error');expect(cue('blocks',{lines:0,moves:0},{lines:2,moves:1})).toBe('clear');expect(cue('blocks',{lines:0,moves:0},{lines:0,moves:1})).toBe('place');expect(cue('blocks',{piece:'T',x:3,y:1},{piece:'T',x:3,y:2})).toBeNull();});
 it('pool friction is silent, collisions and pocketing have distinct cues',()=>{const ball=(vx:number,vy=0,pocketed=false,id=1)=>({id,x:100,y:100,vx,vy,pocketed});expect(cue('billiards',{phase:'moving',balls:[ball(100)]},{phase:'moving',balls:[ball(99)]})).toBeNull();expect(cue('billiards',{balls:[ball(100)]},{balls:[ball(-90)]})).toBe('bounce');expect(cue('billiards',{balls:[ball(0)]},{balls:[ball(75)]})).toBe('bounce');expect(cue('billiards',{balls:[ball(70)]},{balls:[ball(0,0,true)]})).toBe('coin');expect(cue('billiards',{balls:[ball(70,0,false,0)]},{balls:[ball(0,0,true,0)]})).toBe('error');});
 it('maps board, card, clue and error feedback from actual state changes',()=>{expect(cue('solitaire',{moves:0},{moves:1})).toBe('card');expect(cue('chess',{log:[]},{log:['Nf3']})).toBe('move');expect(cue('chess',{log:[]},{log:['Bxe5']})).toBe('place');expect(cue('domino',{chain:[]},{chain:[{}]})).toBe('place');expect(cue('trivia',{phase:'roll'},{phase:'move'},{type:'ROLL'})).toBe('roll');expect(cue('trivia',{}, {},{type:'GRADE',correct:false})).toBe('error');expect(cue('wordle',{guesses:[]},{guesses:[],message:'Invalid word'},{type:'GUESS'})).toBe('error');expect(cue('crossword',{hints:0},{hints:1},{type:'HINT'})).toBe('coin');expect(cue('sudoku',{mistakes:0},{mistakes:1},{type:'NUMBER'})).toBe('error');});
});
describe('audio availability and mute',()=>{
 afterEach(()=>{setSoundEnabled(false);vi.unstubAllGlobals();});
 it('is safe during SSR and with missing Web Audio',async()=>{setSoundEnabled(true);expect(()=>playSound('ui')).not.toThrow();await expect(unlockAudio()).resolves.toBeUndefined();vi.stubGlobal('window',{});await expect(unlockAudio()).resolves.toBeUndefined();});
 it('does not construct or output audio while muted',async()=>{const construct=vi.fn();vi.stubGlobal('window',{AudioContext:construct});setSoundEnabled(false);playSound('success');await unlockAudio();expect(construct).not.toHaveBeenCalled();});
 it('throttles rapid repeated collision events and uses short envelopes',async()=>{let starts=0;const stops:number[]=[];const parameter=()=>({value:0,setTargetAtTime:vi.fn(),setValueAtTime:vi.fn(),exponentialRampToValueAtTime:vi.fn()});class Audio {state='running';currentTime=1;destination={};createGain(){return {gain:parameter(),connect:vi.fn(),disconnect:vi.fn()};}createOscillator(){return {frequency:parameter(),type:'sine',connect:vi.fn(),disconnect:vi.fn(),start:()=>starts++,stop:(time:number)=>stops.push(time),onended:null};}resume(){return Promise.resolve();}}vi.stubGlobal('window',{AudioContext:Audio});setSoundEnabled(true);await unlockAudio();playSound('bounce');playSound('bounce');playSound('bounce');expect(starts).toBe(1);expect(stops[0]).toBeGreaterThan(1);expect(stops[0]).toBeLessThan(1.2);setSoundEnabled(false);playSound('clear');expect(starts).toBe(1);});
});
