import { PixelSprite, suits } from "./PixelSprite";
import type { Sprite } from "./pixel-art";
const artwork: Record<string, Sprite> = {
  snake: [
    "................",
    "..aaa...........",
    ".aaaaa..........",
    "..aaa...........",
    "..........kkkk..",
    "..........kbkk..",
    "......kkkkkkkk..",
    ".....kkkkkkkk...",
    ".....kk.........",
    ".....kk.........",
    ".....kk.........",
    ".....kk.........",
    "..kkkkk.........",
    ".kkkkkk.........",
    ".kk.............",
    "................",
  ],
  runner: [
    "........kkkkkk..",
    ".......kkkkkkk..",
    ".......kkbkkkk..",
    ".......kkkkkkk..",
    ".......kkkk.....",
    ".......kkkkkk...",
    "......kkkk......",
    "k....kkkkk......",
    "kk..kkkkkkkk....",
    "kkkkkkkkkk.k....",
    ".kkkkkkkk.......",
    "..kkkkkk........",
    "....kk.kk.......",
    "....kk..kk......",
    "...kkk..kkk.....",
    "................",
  ],
  flappy: [
    "kk..........kk..",
    "kk..........kk..",
    "kk..........kk..",
    "................",
    "......kkkk......",
    "....kkkkkkkk....",
    "...kkkkkkbkk....",
    "..kkkaakkbkkk...",
    "..kkaaaakkkkaa..",
    "...kkaaakkkkaa..",
    "....kkkkkkkk....",
    "......kkkk......",
    "................",
    "kk..........kk..",
    "kk..........kk..",
    "kk..........kk..",
  ],
  breakout: [
    "................",
    ".kkkk.kkkk.kkkk.",
    ".kkkk.kkkk.kkkk.",
    "................",
    ".kkkk.kkkk......",
    ".kkkk.kkkk......",
    "................",
    "................",
    "...........aa...",
    "..........aaaa..",
    "...........aa...",
    "..........k.....",
    ".........k......",
    "....kkkkkkkkkk..",
    "....kkkkkkkkkk..",
    "................",
  ],
  blocks: [
    "....aa.aa.aa....",
    "....aa.aa.aa....",
    ".......aa.......",
    ".......aa.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".kk..........kk.",
    ".kk..........kk.",
    ".kk....kk.kk.kk.",
    ".kk....kk.kk.kk.",
    ".kk.kk.kk.kk.kk.",
    ".kk.kk.kk.kk.kk.",
    "................",
  ],
  billiards: [
    ".kkkkkkkkkkkkkk.",
    "kkbbbbbbbbbbbbkk",
    "kbbbbbbbbbbbbbbk",
    "kbbbbbbbbbbbbbbk",
    "kbbbkkbbbbbbbbbk",
    "kbbkbbkbbbbbbbbk",
    "kbbkbbkbbbbbbbbk",
    "kbbbkkbbbbbbbbbk",
    "kbbbbbbbbbaabbbk",
    "kbbbbbbbaaaabbbk",
    "kbbbbbbaabbbbbbk",
    "kbbbbbaabbbbbbbk",
    "kbbbbaabbbbbbbbk",
    "kbbbbbbbbbbbbbbk",
    "kkbbbbbbbbbbbbkk",
    ".kkkkkkkkkkkkkk.",
  ],
  domino: [
    "................",
    "....kkkkkkkk....",
    "....kbbbbbbk....",
    "....kbkkbbbk....",
    "....kbkkbbbk....",
    "....kbbbkkbk....",
    "....kbbbkkbk....",
    "....kkkkkkkk....",
    "....kbbbbbbk....",
    "....kbkkbbbk....",
    "....kbkkbbbk....",
    "....kbbbkkbk....",
    "....kbbbkkbk....",
    "....kbbbbbbk....",
    "....kkkkkkkk....",
    "................",
  ],
  chess: [
    ".......kk.......",
    "......kkkk......",
    ".......kk.......",
    "....kkkkkkkk....",
    "...kkbbbbbbkk...",
    "...kkbbbbbbkk...",
    "....kkbbbbkk....",
    ".....kkkkkk.....",
    "......kkkk......",
    "......kkkk......",
    ".....kkkkkk.....",
    "....kkkkkkkk....",
    "...kkkkkkkkkk...",
    "..kkkkkkkkkkkk..",
    "..kkkkkkkkkkkk..",
    "................",
  ],
  solitaire: [
    "...kkkkkkkkkk...",
    "...kbbbbbbbbk...",
    "...kbkkbbbbbk...",
    "...kbkkbbbbbk...",
    "...kbbbbbbbbk...",
    "...kbbbbbbbbk...",
    "...kbbbkkbbbk...",
    "...kbbkkkkbbk...",
    "...kbkkkkkkbk...",
    "...kbbkbbkbbk...",
    "...kbbbkkbbbk...",
    "...kbbbbbbbbk...",
    "...kbbbbkkbbk...",
    "...kbbbbkkbbk...",
    "...kkkkkkkkkk...",
    "................",
  ],
  sudoku: [
    ".kkkkkkkkkkkkkk.",
    ".kbbbkbabkbbbbk.",
    ".kbkbkbbbkbbkbk.",
    ".kbbbkbabkbbbbk.",
    ".kkkkkkkkkkkkkk.",
    ".kbbbkbabkbbbbk.",
    ".kbbbkaaakbkkbk.",
    ".kbbbkbabkbbbbk.",
    ".kkkkkkkkkkkkkk.",
    ".kbkbkbbbkbbbbk.",
    ".kbbbkbkbkbkkbk.",
    ".kbkbkbbbkbbbbk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
  ],
  wordle: [
    "................",
    ".kk.aa.kk.kk.kk.",
    ".kk.aa.kk.kk.kk.",
    "................",
    ".kk.kk.aa.kk.kk.",
    ".kk.kk.aa.kk.kk.",
    "................",
    ".aa.aa.aa.aa.aa.",
    ".aa.aa.aa.aa.aa.",
    "................",
    ".kk.kk.kk.kk.kk.",
    ".kk.kk.kk.kk.kk.",
    "................",
    ".kk.kk.kk.kk.kk.",
    ".kk.kk.kk.kk.kk.",
    "................",
  ],
  crossword: [
    "................",
    ".kkkkkkkkkkkkkk.",
    ".kbbbkkbbbkbbbk.",
    ".kbkbkkbkbkbkbk.",
    ".kbbbkkbbbkbbbk.",
    ".kkkkkkkkkkkkkk.",
    ".kbbbkbabkkkkkk.",
    ".kbkbkaaakkkkkk.",
    ".kbbbkbabkkkkkk.",
    ".kkkkkkkkkkkkkk.",
    ".kkkkkkbbbkbbbk.",
    ".kkkkkkbkbkbkbk.",
    ".kkkkkkbbbkbbbk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  ring: [
    ".....aa.aa......",
    "...aa.....aa....",
    "..aa.......aa...",
    ".aa.........aa..",
    ".aa...kkkk..aa..",
    "aa...kk..kk..aa.",
    "aa.......kk..aa.",
    ".....kkkkk......",
    "aa...kk......aa.",
    "aa...........aa.",
    ".aa..kk.....aa..",
    ".aa.........aa..",
    "..aa.......aa...",
    "...aa.....aa....",
    ".....aa.aa......",
    "................",
  ],
  letters: [
    "................",
    "..kkkkkkkkkkkk..",
    "..kbbbbbbbbbbk..",
    "..kbbbkkkbbbbk..",
    "..kbbkkbkkbbbk..",
    "..kbbkkbkkbbbk..",
    "..kbbkkkkkbbbk..",
    "..kbbkkbkkbbbk..",
    "..kbbkkbkkbbbk..",
    "..kbbkkbkkbbbk..",
    "..kbbbbbbbbbbk..",
    "..kbbbbbbbaabk..",
    "..kbbbbbbbaabk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
  ],
  trivia: [
    ".....kkkkkk.....",
    "...kkbbbbbbkk...",
    "..kbbaaabbbbbk..",
    ".kbbabbaaabbbbk.",
    ".kbbaaabaaabbbk.",
    "kbbbbaaabaabbbbk",
    "kbbbbbbaaabbbbbk",
    "kbbbbbaaaabbbbbk",
    "kbbbaaaabbbbbbbk",
    "kbbbaaaabbbbbbbk",
    "kbbbbaabbbbbbbbk",
    ".kbbbabbbbbbbbk.",
    ".kbbbbbbbbbbbbk.",
    "..kbbbbbbbbbbk..",
    "...kkbbbbbbkk...",
    ".....kkkkkk.....",
  ],
};
artwork.poker = suits[0];
export function GameIcon({
  id,
  fallback = "?",
}: {
  id: string;
  fallback?: string;
}) {
  return artwork[id] ? (
    <PixelSprite
      className="collection-sprite"
      sprite={artwork[id]}
      palette={{ k: "currentColor", a: "var(--accent)", b: "var(--raised)" }}
    />
  ) : (
    <span aria-hidden="true">{fallback}</span>
  );
}
