import { difficulty, labels, select, tr, type GameDefinition, type GameViewProps } from '../../core/types';
import { createDomino, dominoBot, dominoReducer, legalEnds, legalTiles, pipSum, tiles, type DominoState } from './engine';
import './domino.css';
const positions:Record<number,[number,number][]>= {0:[],1:[[15,15]],2:[[7,7],[23,23]],3:[[7,7],[15,15],[23,23]],4:[[7,7],[23,7],[7,23],[23,23]],5:[[7,7],[23,7],[15,15],[7,23],[23,23]],6:[[7,7],[23,7],[7,15],[23,15],[7,23],[23,23]]};
function Pip({value}:{value:number}){return <svg viewBox="0 0 30 30" aria-hidden="true">{positions[value].map(([x,y],i)=><circle key={i} cx={x} cy={y} r="2.5" />)}</svg>;}
function Tile({left,right}:{left:number;right:number}){return <span className="domino-tile" aria-label={`${left}–${right}`}><Pip value={left}/><Pip value={right}/></span>;}
function DominoView({state:s,dispatch,locale:l,config:c,paused}:GameViewProps<DominoState>) {
  const human=s.turn<Number(c.humans||1);const hand=s.hands[s.turn];const can=legalTiles(s);return <div className="domino-game"><div className="domino-scores">{s.hands.map((h,i)=><div key={i} className={i===s.turn?'active':''}><strong>{tr(l,'Jugador','Player')} {i+1}{c.mode==='pairs'?` · ${tr(l,'Equipo','Team')} ${i%2+1}`:''}</strong><span>{s.points[i]} {tr(l,'puntos','points')} · {h.length} {tr(l,'fichas','tiles')}</span></div>)}</div>
    <div className="domino-chain" aria-label={tr(l,'Cadena de fichas','Tile chain')}>{s.chain.length?s.chain.map((tile,i)=><Tile key={i} left={tile.left} right={tile.right}/>):<p>{tr(l,'Comienza con','Begin with')} <Tile left={tiles[s.opening][0]} right={tiles[s.opening][1]}/></p>}</div>
    <p role="status">{s.event[l]}</p>{s.phase==='roundover'?<><div className="domino-reveal">{s.hands.map((h,i)=><div key={i}><strong>{tr(l,'Jugador','Player')} {i+1}: {pipSum(h)}</strong><div>{h.map(id=><Tile key={id} left={tiles[id][0]} right={tiles[id][1]}/>)}</div></div>)}</div>{s.status==='playing'&&<button disabled={paused} onClick={()=>dispatch({type:'NEXT_ROUND'})}>{tr(l,'Siguiente ronda','Next round')}</button>}</>:<>
      <h3>{tr(l,'Fichas de','Tiles of')} {tr(l,'jugador','player')} {s.turn+1}</h3><div className="domino-rack">{human?hand.map(id=><div key={id} className={`domino-choice ${can.includes(id)?'legal':''}`}><Tile left={tiles[id][0]} right={tiles[id][1]}/><div>{legalEnds(s,id).map(end=><button key={end} disabled={paused} aria-label={`${tr(l,'Colocar','Play')} ${tiles[id].join('-')} ${end==='left'?tr(l,'a la izquierda','on the left'):tr(l,'a la derecha','on the right')}`} onClick={()=>dispatch({type:'PLAY',id,end})}>{end==='left'?'←':'→'}</button>)}</div></div>):hand.map((_,i)=><span key={i} className="domino-hidden" aria-label={tr(l,'Ficha oculta','Hidden tile')}>···</span>)}</div>
      <div className="domino-actions">{c.mode!=='pairs'&&<button disabled={paused||can.length>0||!s.stock.length} onClick={()=>dispatch({type:'DRAW'})}>{tr(l,'Robar','Draw')} · {s.stock.length}</button>}<button disabled={paused||can.length>0||(c.mode!=='pairs'&&s.stock.length>0)} onClick={()=>dispatch({type:'PASS'})}>{tr(l,'Pasar','Pass')}</button><span>{tr(l,'Extremos','Ends')}: {s.chain.length?`${s.chain[0].left} / ${s.chain.at(-1)!.right}`:'—'}</span></div></>}
  </div>;
}
export const domino:GameDefinition<DominoState>={id:'domino',name:labels('Dominó','Dominoes'),description:labels('Doble seis, individual o por parejas.','Double six, individual or in pairs.'),category:'board',icon:'⚅',version:1,defaults:{mode:'draw',players:2,humans:1,difficulty:'medium',target:100},options:[select('mode','Modalidad','Mode',[['draw','Individual con robo','Individual draw'],['pairs','Parejas · 4 jugadores','Partners · 4 players']],'draw'),select('players','Jugadores','Players',[[2,'2','2'],[3,'3','3'],[4,'4','4']],2,c=>c.mode!=='pairs'),select('humans','Humanos','Humans',[[1,'1','1'],[2,'2','2'],[3,'3','3'],[4,'4','4']],1),select('target','Objetivo de puntos','Point target',[[50,'50','50'],[100,'100','100'],[200,'200','200']],100),{...difficulty,visibleWhen:c=>Number(c.humans)<(c.mode==='pairs'?4:Number(c.players))}],playerCount:c=>c.mode==='pairs'?4:Number(c.players),create:createDomino,reducer:dominoReducer,View:DominoView,bot:dominoBot,getTurn:(s,c)=>s.phase==='roundover'?null:{player:s.turn,bot:s.turn>=Math.min(s.hands.length,Number(c.humans)||1),hidden:true},guide:[
  {title:labels('Haz coincidir los extremos','Match the ends'),text:labels('Cada jugador recibe siete fichas. Abre el doble más alto repartido, o la ficha de mayor suma si no hay dobles. Encaja un número en un extremo libre. Las flechas de una ficha indican dónde puedes jugarla.','Each player receives seven tiles. Open with the highest dealt double, or the highest-total tile if no doubles were dealt. Match a number to either free end. Arrows show where you can play.'),diagram:'[2|6] [6|6] [6|3] → siguiente: 2 o 3'},
  {title:labels('Robar o pasar','Draw or pass'),text:labels('Si no tienes jugada en individual, roba hasta poder jugar o agotar el montón; entonces pasa. En parejas no se roba y se sientan juntos los jugadores 1+3 y 2+4.','When you cannot play in individual mode, draw until you can play or the stock runs out; then pass. Partners do not draw. Players 1+3 and 2+4 share teams.'),diagram:'1 ↔ 3     2 ↔ 4'},
  {title:labels('Vacía la mano o cierra','Empty your hand or block'),text:labels('Quien coloca su última ficha gana la ronda. Si todos pasan consecutivamente, gana la menor suma de puntos restantes, o la menor suma por equipo. Un empate no puntúa. La ronda suma los puntos que quedan en las manos rivales. El primero en llegar al objetivo gana la partida.','Play your last tile to win the round. When everyone passes consecutively, the lowest remaining pip total wins, or the lowest team total. Ties score nothing. Winners receive the remaining opponents’ pips. First to the target wins.'),diagram:'Tu mano: [0|1] = 1 · Rival: [4|6] = 10 → +10'}],summarize:s=>({rounds:s.round,points:s.points[0]})};
