import { baseState, type Action, type Config, type GameState } from '../../core/types';
import { shuffle } from '../../core/random';
export const PIECES=['I','O','T','S','Z','J','L'] as const;
export type Piece=typeof PIECES[number];
type Cell=[number,number];
const modern:Record<Piece,Cell[]>={I:[[0,1],[1,1],[2,1],[3,1]],O:[[1,0],[2,0],[1,1],[2,1]],T:[[1,0],[0,1],[1,1],[2,1]],S:[[1,0],[2,0],[0,1],[1,1]],Z:[[0,0],[1,0],[1,1],[2,1]],J:[[0,0],[0,1],[1,1],[2,1]],L:[[2,0],[0,1],[1,1],[2,1]]};
// Independently encoded geometry of the Nintendo right-handed rotation system.
const nes:Record<Piece,Cell[][]>={
 T:[[[-1,0],[0,0],[1,0],[0,1]],[[0,-1],[-1,0],[0,0],[0,1]],[[-1,0],[0,0],[1,0],[0,-1]],[[0,-1],[0,0],[1,0],[0,1]]],
 J:[[[-1,0],[0,0],[1,0],[1,1]],[[0,-1],[0,0],[-1,1],[0,1]],[[-1,-1],[-1,0],[0,0],[1,0]],[[0,-1],[1,-1],[0,0],[0,1]]],
 L:[[[-1,0],[0,0],[1,0],[-1,1]],[[-1,-1],[0,-1],[0,0],[0,1]],[[1,-1],[-1,0],[0,0],[1,0]],[[0,-1],[0,0],[0,1],[1,1]]],
 Z:[[[-1,0],[0,0],[0,1],[1,1]],[[1,-1],[0,0],[1,0],[0,1]]],
 S:[[[0,0],[1,0],[-1,1],[0,1]],[[0,-1],[0,0],[1,0],[1,1]]],
 O:[[[-1,0],[0,0],[-1,1],[0,1]]],I:[[[-2,0],[-1,0],[0,0],[1,0]],[[0,-2],[0,-1],[0,0],[0,1]]]
};
const jKicks:Record<string,Cell[]>={ '0>1':[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],'1>0':[[0,0],[1,0],[1,1],[0,-2],[1,-2]],'1>2':[[0,0],[1,0],[1,1],[0,-2],[1,-2]],'2>1':[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],'2>3':[[0,0],[1,0],[1,-1],[0,2],[1,2]],'3>2':[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],'3>0':[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],'0>3':[[0,0],[1,0],[1,-1],[0,2],[1,2]]};
const iKicks:Record<string,Cell[]>={'0>1':[[0,0],[-2,0],[1,0],[-2,1],[1,-2]],'1>0':[[0,0],[2,0],[-1,0],[2,-1],[-1,2]],'1>2':[[0,0],[-1,0],[2,0],[-1,-2],[2,1]],'2>1':[[0,0],[1,0],[-2,0],[1,2],[-2,-1]],'2>3':[[0,0],[2,0],[-1,0],[2,-1],[-1,2]],'3>2':[[0,0],[-2,0],[1,0],[-2,1],[1,-2]],'3>0':[[0,0],[1,0],[-2,0],[1,2],[-2,-1]],'0>3':[[0,0],[-1,0],[2,0],[-1,-2],[2,1]]};
export interface BlocksState extends GameState { board:(Piece|null)[][];piece:Piece;x:number;y:number;rotation:number;queue:Piece[];hold:Piece|null;held:boolean;lines:number;level:number;elapsed:number;frame:number;accumulator:number;gravity:number;lock:number;resets:number;delay:number;combo:number;b2b:boolean;profile:string;input:{left:boolean;right:boolean;down:boolean};das:number;horizontal:number;pending:string[];lastRotate:boolean;kick:number;dropPoints:number;nesSeed:number;spawnCount:number;spawnId:number;[key:string]:any }
export function cells(s:BlocksState,x=s.x,y=s.y,rotation=s.rotation):Cell[]{let shape:Cell[];if(s.profile==='classic')shape=nes[s.piece][rotation%nes[s.piece].length];else{shape=modern[s.piece];if(s.piece!=='O'){const center=s.piece==='I'?1.5:1;for(let r=0;r<rotation;r++)shape=shape.map(([a,b])=>[center-(b-center),center+(a-center)]);}}return shape.map(([a,b])=>[a+x,b+y]);}
export function valid(s:BlocksState,x=s.x,y=s.y,r=s.rotation){return cells(s,x,y,r).every(([a,b])=>a>=0&&a<10&&b>=-2&&b<20&&(b<0||!s.board[b][a]));}
export function nesAdvance(seed:number){const low=seed&255,high=(seed>>>8)&255;const feedback=((low>>>1)^(high>>>1))&1;return ((high>>>1)|((low&1)<<7))<<8 | (low>>>1)|(feedback<<7);}
const spawnPieces:Piece[]=['T','J','Z','O','S','L','I'];const spawnIds=[2,7,8,10,11,14,18];
export function drawPiece(s:BlocksState):Piece {if(s.profile==='classic'){s.spawnCount=(s.spawnCount+1)&255;let n=((s.nesSeed&255)+s.spawnCount)&7;if(n===7||spawnIds[n]===s.spawnId){s.nesSeed=nesAdvance(s.nesSeed);n=((s.nesSeed&7)+s.spawnId)%7;}s.spawnId=spawnIds[n];return spawnPieces[n];}if(s.queue.length<6){const bag=shuffle(PIECES,s.rng);s.rng=bag.seed;s.queue.push(...bag.items);}return s.queue.shift()!;}
function spawn(s:BlocksState,piece?:Piece){s.piece=piece||drawPiece(s);s.rotation=0;s.x=s.profile==='classic'?5:3;s.y=s.profile==='classic'?0:-1;s.gravity=0;s.lock=0;s.resets=0;s.held=false;s.lastRotate=false;s.dropPoints=0;if(!valid(s))s.status='lost';}
export function createBlocks(c:Config,seed:number):BlocksState {const s:BlocksState={...baseState(seed),board:Array.from({length:20},()=>Array(10).fill(null)),piece:'T',x:3,y:-1,rotation:0,queue:[],hold:null,held:false,lines:0,level:Number(c.level)||0,elapsed:0,frame:0,accumulator:0,gravity:0,lock:0,resets:0,delay:0,combo:-1,b2b:false,profile:String(c.profile||'modern'),input:{left:false,right:false,down:false},das:0,horizontal:0,pending:[],lastRotate:false,kick:0,dropPoints:0,nesSeed:seed&65535||0x8988,spawnCount:0,spawnId:0};spawn(s);if(s.profile==='classic'){s.nesSeed=nesAdvance(s.nesSeed);s.queue=[drawPiece(s)];}return s;}
function resetLock(s:BlocksState){if(s.profile!=='classic'&&s.resets<15&&!valid(s,s.x,s.y+1)){s.lock=0;s.resets++;}}
export function rotate(s:BlocksState,dir:number){const count=s.profile==='classic'?nes[s.piece].length:4;const r=(s.rotation+dir+count)%count;const kicks=s.profile==='classic'||s.piece==='O'?[[0,0]]:(s.piece==='I'?iKicks:jKicks)[`${s.rotation}>${r}`];for(let i=0;i<kicks.length;i++){const [x,y]=kicks[i];if(valid(s,s.x+x,s.y+y,r)){s.x+=x;s.y+=y;s.rotation=r;s.lastRotate=true;s.kick=i;resetLock(s);return true;}}return false;}
function shift(s:BlocksState,dir:number){if(valid(s,s.x+dir)){s.x+=dir;s.lastRotate=false;resetLock(s);return true;}return false;}
export function nesGravity(level:number){return [48,43,38,33,28,23,18,13,8,6,5,5,5,4,4,4,3,3,3,2,2,2,2,2,2,2,2,2,2,1][Math.min(29,Math.max(0,level))];}
export function ghostY(s:BlocksState){let y=s.y;while(valid(s,s.x,y+1))y++;return y;}
export function lockPiece(s:BlocksState,c:Config){
  let spin=false,mini=false;if(s.profile!=='classic'&&s.piece==='T'&&s.lastRotate){const cx=s.x+1,cy=s.y+1;const occupied=(x:number,y:number)=>x<0||x>9||y>19||(y>=0&&!!s.board[y][x]);const corners=[occupied(cx-1,cy-1),occupied(cx+1,cy-1),occupied(cx+1,cy+1),occupied(cx-1,cy+1)];spin=corners.filter(Boolean).length>=3;const front=[[0,1],[1,2],[2,3],[3,0]][s.rotation];mini=spin&&!(corners[front[0]]&&corners[front[1]])&&s.kick!==4;}
  const positions=cells(s);if(positions.some(([,y])=>y<0)){s.status='lost';return;}for(const [x,y]of positions)s.board[y][x]=s.piece;
  const n=s.board.filter(row=>row.every(Boolean)).length;s.board=s.board.filter(row=>!row.every(Boolean));while(s.board.length<20)s.board.unshift(Array(10).fill(null));
  const hard=n===4||(spin&&n>0);let points=0;if(s.profile==='classic')points=[0,40,100,300,1200][n]*(s.level+1)+s.dropPoints;else{points=(spin?(mini?[100,200,400][n]:[400,800,1200,1600][n]):[0,100,300,500,800][n])*(s.level+1);if(hard&&s.b2b)points*=1.5;if(n){s.combo++;points+=50*s.combo*(s.level+1);s.b2b=hard;}else s.combo=-1;}
  s.score+=points;s.lines+=n;s.moves++;
  if(s.profile==='classic'){const start=Number(c.level)||0;const threshold=Math.min((start+1)*10,Math.max(100,start*10-50));s.level=start+(s.lines>=threshold?1+Math.floor((s.lines-threshold)/10):0);const bottom=Math.max(...positions.map(([,y])=>y));s.delay=Math.min(18,10+Math.floor((21-bottom)/4)*2)+(n?20-(s.frame%4):0);s.message=n?`${n} +${points}`:'';}else{s.level=(Number(c.level)||0)+Math.floor(s.lines/10);s.delay=0;s.message=spin?`${mini?'Mini ':''}T-spin +${points}`:n?`${n} +${points}`:'';}
  if(c.mode==='lines'&&s.lines>=Number(c.target||40)){s.status='won';return;}if(s.profile!=='classic')spawn(s);
}
function frame(s:BlocksState,c:Config){s.frame++;const fps=s.profile==='classic'?60.0988138974405:60;s.elapsed+=1/fps;if(c.mode==='time'&&s.elapsed>=Number(c.time||120)){s.status='won';return;}if(s.profile==='classic')s.nesSeed=nesAdvance(s.nesSeed);
  if(s.delay){s.pending=[];s.delay--;if(!s.delay){const next=s.queue.shift()!;spawn(s,next);s.queue=[drawPiece(s)];}return;}
  for(const p of s.pending){if(p==='CW')rotate(s,1);if(p==='CCW')rotate(s,-1);if(p==='LEFT'&&(!s.input.down||s.profile!=='classic'))shift(s,-1);if(p==='RIGHT'&&(!s.input.down||s.profile!=='classic'))shift(s,1);if(p==='HARD'&&s.profile!=='classic'){const y=ghostY(s);s.score+=(y-s.y)*2;s.y=y;lockPiece(s,c);s.pending=[];return;}if(p==='HOLD'&&s.profile!=='classic'&&!s.held){const old=s.piece,hold=s.hold;spawn(s,hold||undefined);s.hold=old;s.held=true;}}s.pending=[];if(s.status!=='playing')return;
  const dir=s.input.right?1:s.input.left?-1:0;if(s.profile==='classic'&&s.input.down){/* Nintendo suppresses horizontal processing during soft drop. */}else if(dir){if(dir!==s.horizontal){s.das=0;s.horizontal=dir;}else{s.das++;if(s.profile==='classic'){if(s.das>=16){s.das=10;if(!shift(s,dir))s.das=16;}}else if(s.das>=10&&(s.das-10)%2===0)shift(s,dir);}}else{s.horizontal=0;if(s.profile!=='classic')s.das=0;}
  s.gravity++;const period=s.profile==='classic'?(s.input.down&&!s.input.left&&!s.input.right?2:nesGravity(s.level)):s.input.down?2:Math.max(1,Math.round(60*Math.pow(Math.max(0.1,0.8-s.level*0.007),s.level)));
  if(s.gravity>=period){s.gravity=0;if(valid(s,s.x,s.y+1)){s.y++;if(s.input.down){if(s.profile==='classic')s.dropPoints++;else s.score++;}}else if(s.profile==='classic'){lockPiece(s,c);return;}}
  if(s.profile!=='classic'){if(!valid(s,s.x,s.y+1)){s.lock++;if(s.lock>=30)lockPiece(s,c);}else s.lock=0;}
}
export function blocksReducer(state:BlocksState,a:Action,c:Config):BlocksState {if(state.status!=='playing')return state;const s=structuredClone(state);if(a.type==='RELEASE'){s.input={left:false,right:false,down:false};s.pending=[];s.horizontal=0;return s;}if(['LEFT','RIGHT','DOWN'].includes(a.type)){const key=a.type.toLowerCase() as 'left'|'right'|'down';s.input[key]=a.down!==false;if(a.down!==false&&!a.repeat&&a.type!=='DOWN'){s.pending.push(a.type);s.horizontal=a.type==='LEFT'?-1:1;s.das=0;}return s;}if(['CW','CCW','HARD','HOLD'].includes(a.type)&&a.down!==false&&!a.repeat){s.pending.push(a.type);return s;}if(a.type!=='TICK')return s;const fps=s.profile==='classic'?60.0988138974405:60;s.accumulator+=Math.max(0,Math.min(1,Number(a.dt)||0))*fps;while(s.accumulator+1e-8>=1&&s.status==='playing'){s.accumulator-=1;frame(s,c);}return s;}
