import { useEffect } from 'react';
import { labels, select, tr, type GameDefinition, type GameViewProps, type GuideStep } from '../../core/types';
import { CanvasBoard, Message, TouchControls } from '../../ui/shared';
import { arcadeReducer, createArcade, type ArcadeState } from './engines';
import { blocksReducer, cells, createBlocks, ghostY, type BlocksState, type Piece } from './blocks';
const directionKeys={ArrowLeft:'LEFT',ArrowRight:'RIGHT',ArrowUp:'UP',ArrowDown:'DOWN',a:'LEFT',d:'RIGHT',w:'UP',s:'DOWN'};
const jumpKeys={' ':'JUMP',ArrowUp:'JUMP',w:'JUMP'};
const paddleKeys={ArrowLeft:'LEFT',ArrowRight:'RIGHT',a:'LEFT',d:'RIGHT'};
const blocksKeys={ArrowLeft:'LEFT',ArrowRight:'RIGHT',ArrowDown:'DOWN',ArrowUp:'CW',x:'CW',z:'CCW',' ':'HARD',c:'HOLD',Shift:'HOLD'};
function text(ctx:CanvasRenderingContext2D,s:string,x:number,y:number,c:string,size=18){ctx.fillStyle=c;ctx.font=`${size}px monospace`;ctx.fillText(s,x,y);}
function drawArcade(ctx:CanvasRenderingContext2D,s:ArcadeState,c:Record<string,string>){ctx.fillStyle=c.bg||'#111';ctx.fillRect(0,0,720,440);ctx.fillStyle=c.accent||'#e43e42';ctx.strokeStyle=c.border||'#555';ctx.lineWidth=1;
  if(s.kind==='snake'){const cell=19,x=170,y=25;ctx.strokeRect(x,y,380,380);for(const [a,b]of s.snake){ctx.fillStyle=a===s.snake[0][0]&&b===s.snake[0][1]?c.text:c.accent;ctx.fillRect(x+a*cell+2,y+b*cell+2,15,15);}ctx.fillStyle=c.text;ctx.beginPath();ctx.arc(x+s.food[0]*cell+9,y+s.food[1]*cell+9,6,0,Math.PI*2);ctx.fill();}
  if(s.kind==='runner'){ctx.strokeStyle=c.text;ctx.beginPath();ctx.moveTo(0,380);ctx.lineTo(720,380);ctx.stroke();ctx.fillStyle=c.accent;ctx.fillRect(85,342-s.y,28,38);ctx.fillStyle=c.text;for(const o of s.obstacles)ctx.fillRect(o.x,380-o.h,o.w,o.h);for(let i=0;i<12;i++){const x=(i*70-s.elapsed*s.speed/2)%840;ctx.fillStyle=c.border;ctx.fillRect(x,395,24,2);}}
  if(s.kind==='flappy'){ctx.fillStyle=c.accent;ctx.beginPath();ctx.arc(150,s.y,12,0,Math.PI*2);ctx.fill();ctx.fillStyle=c.text;ctx.fillRect(154,s.y-3,13,6);for(const p of s.pipes){ctx.fillStyle=c.border;ctx.fillRect(p.x,0,58,p.gap-72);ctx.fillRect(p.x,p.gap+72,58,440-p.gap-72);ctx.fillStyle=c.accent;ctx.fillRect(p.x,p.gap-78,58,6);ctx.fillRect(p.x,p.gap+72,58,6);}}
  if(s.kind==='breakout'){for(const b of s.bricks){if(!b.hp)continue;ctx.fillStyle=b.hp>1?c.text:c.accent;ctx.fillRect(b.x,b.y,58,18);}ctx.fillStyle=c.text;ctx.fillRect(s.paddle-55,398,110,9);ctx.beginPath();ctx.arc(s.x,s.y,7,0,Math.PI*2);ctx.fill();text(ctx,`♥ ${s.lives} · ${s.level}`,16,425,c.muted);}
  text(ctx,String(s.score).padStart(5,'0'),18,25,c.text);if(s.status!=='playing')text(ctx,s.status==='won'?'✓':'×',635,55,c.accent,40);
}
function ArcadeView({state,dispatch,paused,locale}:GameViewProps<ArcadeState>){useEffect(()=>{if(!paused)dispatch({type:'RELEASE'});},[paused]);const kind=state.kind;const keys=kind==='snake'?directionKeys:kind==='breakout'?paddleKeys:jumpKeys;return <div><CanvasBoard state={state} dispatch={dispatch} paused={paused} draw={drawArcade} keys={keys}/><TouchControls dispatch={dispatch} controls={kind==='snake'?[['LEFT','←'],['UP','↑'],['DOWN','↓'],['RIGHT','→']]:kind==='breakout'?[['LEFT','←'],['RIGHT','→']]:[['JUMP',tr(locale,'Saltar / Impulso','Jump / Flap')]]}/><p className="muted">{kind==='snake'?tr(locale,'Flechas o WASD · Evita muros y tu cuerpo.','Arrows or WASD · Avoid walls and your body.'):kind==='breakout'?tr(locale,'Ratón, toque o ← → · Golpea con los extremos para cambiar el ángulo.','Pointer, touch or ← → · Paddle edges change the angle.'):tr(locale,'Espacio, ↑ o toca el tablero.','Space, ↑ or tap the board.')}</p></div>;}
const fallback:Record<Piece,string>={I:'#35b6c2',O:'#d1a72d',T:'#a77fdb',S:'#65a46d',Z:'#d95a61',J:'#568cce',L:'#dc9352'};
function drawBlocks(ctx:CanvasRenderingContext2D,s:BlocksState,c:Record<string,string>){ctx.fillStyle=c.bg||'#111';ctx.fillRect(0,0,620,640);const size=28,ox=55,oy=40;ctx.fillStyle=c.surface||'#222';ctx.fillRect(ox,oy,280,560);
  const paint=(x:number,y:number,p:Piece,ghost=false)=>{if(y<0)return;ctx.fillStyle=c[`piece-${p.toLowerCase()}`]||fallback[p];if(ghost){ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=2;ctx.strokeRect(ox+x*size+3,oy+y*size+3,22,22);}else{ctx.fillRect(ox+x*size+1,oy+y*size+1,26,26);text(ctx,p,ox+x*size+9,oy+y*size+19,c.bg||'#111',12);}};
  s.board.forEach((row,y)=>row.forEach((p,x)=>{ctx.strokeStyle=c.border;ctx.strokeRect(ox+x*size,oy+y*size,size,size);if(p)paint(x,y,p);}));if(!s.delay){if(s.profile!=='classic')for(const [x,y]of cells(s,s.x,ghostY(s)))paint(x,y,s.piece,true);for(const [x,y]of cells(s))paint(x,y,s.piece);}
  text(ctx,'LEVEL',365,65,c.muted);text(ctx,String(s.level),365,95,c.text,26);text(ctx,'LINES',365,145,c.muted);text(ctx,String(s.lines),365,175,c.text,26);text(ctx,'SCORE',365,225,c.muted);text(ctx,String(s.score),365,255,c.text,24);text(ctx,'NEXT',365,305,c.muted);
  const next=s.queue.length?s.queue:[s.piece];text(ctx,next.slice(0,s.profile==='classic'?1:5).join(' · '),365,335,c.accent,18);if(s.profile!=='classic'){text(ctx,'HOLD',365,395,c.muted);text(ctx,s.hold||'—',365,425,c.accent,24);}text(ctx,`${Math.floor(s.elapsed)}s`,365,480,c.text);text(ctx,s.profile==='classic'?'NES NTSC':'SRS / 7 BAG',55,625,c.muted,14);}
function BlocksView({state,config,dispatch,paused,locale}:GameViewProps<BlocksState>){useEffect(()=>{if(!paused)dispatch({type:'RELEASE'});},[paused]);return <div><CanvasBoard width={620} height={640} state={state} dispatch={dispatch} paused={paused} keys={blocksKeys} draw={drawBlocks}/><TouchControls dispatch={dispatch} controls={config.profile==='classic'?[['LEFT','←'],['RIGHT','→'],['DOWN','↓'],['CCW','↶'],['CW','↷']]:[['LEFT','←'],['RIGHT','→'],['DOWN','↓'],['CCW','↶'],['CW','↷'],['HARD','⤓'],['HOLD','C']]}/><Message>{state.message}</Message><p>{tr(locale,'← → mover · ↓ descenso · Z/X girar','← → move · ↓ soft drop · Z/X rotate')}{config.profile!=='classic'?tr(locale,' · Espacio caída · C reserva',' · Space hard drop · C hold'):''}</p></div>;}
const guide=(es:string,en:string,textEs:string,textEn:string,diagram:string,action?:any):GuideStep=>({title:labels(es,en),text:labels(textEs,textEn),diagram,action});
const arcade=(id:string,es:string,en:string,descEs:string,descEn:string,icon:string,guides:GuideStep[],options:GameDefinition['options']=[]):GameDefinition<ArcadeState>=>({id,name:labels(es,en),description:labels(descEs,descEn),category:'arcade',icon,version:1,defaults:Object.fromEntries(options.map(o=>[o.key,o.default])),options,create:(c,seed)=>createArcade(id,c,seed),reducer:arcadeReducer,View:ArcadeView,guide:guides,summarize:s=>({score:s.score,seconds:Math.floor(s.elapsed)})});
export const arcadeGames:GameDefinition[]=[
 arcade('snake','Serpiente','Snake','Una cuadrícula, comida y reflejos.','A grid, food and reflexes.','↳',[
 guide('Crece sin chocar','Grow without crashing','Dirige la cabeza con las flechas. Cada alimento suma 10 puntos y alarga el cuerpo. Tocar el muro o tu cuerpo termina la partida.','Steer with the arrows. Each food adds 10 points and extends your body. Hitting a wall or yourself ends the game.','● → → ◇\n    ↑\n    ●', {type:'UP',down:true}),
 guide('Anticipa el siguiente giro','Plan your next turn','El giro se aplica en el siguiente paso. No puedes invertir directamente el sentido; sí puedes entrar en la casilla que la cola acaba de dejar. Completar la cuadrícula gana la partida.','A turn applies on the next step. You cannot reverse directly; you may enter the cell your tail is leaving. Fill the grid to win.','← ● ●\n    ●\n    ●')
 ],[select('speed','Velocidad','Speed',[['slow','Lenta','Slow'],['normal','Normal','Normal'],['fast','Rápida','Fast']],'normal')]),
 arcade('runner','Carrera de pulso','Pulse Runner','Salta y aguanta a medida que sube la velocidad.','Jump and survive as speed increases.','⌁',[
 guide('Salta sobre los obstáculos','Jump over obstacles','Espacio, flecha arriba o un toque lanza un salto. Espera a volver al suelo antes de saltar otra vez.','Space, up arrow or a tap launches a jump. Land before jumping again.','  ↗ ■ ↘\n──────▥────',{type:'JUMP',down:true}),
 guide('El ritmo acelera','The pace accelerates','Los puntos aumentan con el tiempo y los obstáculos se acercan cada vez más deprisa. La velocidad máxima está limitada para mantenerlo jugable.','Points increase with time and obstacles approach faster. Speed has a maximum to keep the game playable.','■     ▥   ▥ ←')
 ]),
 arcade('flappy','Vuelo de pulso','Pulse Flight','Encuentra el ritmo para atravesar cada abertura.','Find the rhythm through each opening.','⋔',[
 guide('Un toque, un impulso','One tap, one flap','Cada pulsación de espacio, arriba o un toque da impulso hacia arriba. La gravedad te devuelve hacia abajo. Mantener pulsado no da impulsos repetidos.','Each press of space, up or tap pushes upwards. Gravity pulls down. Holding the key does not repeatedly flap.','   ↑\n   ● →   ▥\n   ↓',{type:'JUMP',down:true}),
 guide('Atraviesa el hueco','Pass through the gap','Cruza sin tocar los tubos ni los límites superior e inferior. Cada pareja superada suma un punto.','Cross without touching pipes or the upper and lower boundaries. Every passed pair scores one point.','▥       ▥\n   ● →\n▥       ▥')
 ]),
 arcade('breakout','Rompebloques','Brick Breaker','Controla los rebotes y limpia cada nivel.','Control rebounds and clear every level.','▤',[
 guide('Mueve la pala','Move the paddle','Usa ← →, el ratón o arrastra sobre el tablero. Impide que la pelota caiga; tienes tres vidas.','Use ← →, the pointer or drag on the board. Keep the ball from falling; you have three lives.','▤ ▤ ▤ ▤\n   ● ↙\n ← ═══ →'),
 guide('El ángulo importa','Angles matter','Golpear cerca del centro devuelve la pelota hacia arriba; los extremos la envían en diagonal. Cada golpe a un ladrillo suma 10 puntos. Tras limpiar el tablero llega otro nivel.','The centre sends the ball upwards; paddle edges send it diagonally. Each brick hit scores 10 points. Clear the board to advance.','  ↖  ↑  ↗\n    ═══')
 ]),
 {id:'blocks',name:labels('Caída de bloques','Falling Blocks'),description:labels('Dos sistemas de juego, un tablero de 10 × 20.','Two rule profiles, one 10 × 20 board.'),category:'arcade',icon:'▦',version:1,defaults:{profile:'modern',mode:'infinite',level:0,target:40,time:120},options:[select('profile','Perfil','Profile',[['modern','Moderno SRS','Modern SRS'],['classic','Clásico NES NTSC','Classic NES NTSC']],'modern'),select('mode','Objetivo','Goal',[['infinite','Infinito','Endless'],['time','Contrarreloj','Timed'],['lines','Líneas','Lines']],'infinite'),select('level','Nivel inicial','Starting level',[[0,'0','0'],[9,'9','9'],[18,'18','18'],[19,'19','19'],[29,'29','29']],0),select('target','Líneas objetivo','Target lines',[[20,'20','20'],[40,'40','40'],[100,'100','100']],40),select('time','Tiempo','Time',[[60,'1 min','1 min'],[120,'2 min','2 min'],[300,'5 min','5 min']],120)],create:createBlocks,reducer:blocksReducer,View:BlocksView,guide:[
 guide('Completa filas','Complete rows','Mueve con ← → y gira con X/↑ o Z. Una fila completa desaparece. La velocidad aumenta al subir de nivel; la pila no puede alcanzar la entrada.','Move with ← → and rotate with X/↑ or Z. A complete row disappears. Speed increases with levels; keep the stack below the entrance.','··········\n■■■■  ■■■■\n    ■■',{type:'CW',down:true}),
 guide('Perfil moderno','Modern profile','SRS permite ajustes al girar junto a paredes. Hay bolsa de siete piezas, sombra, reserva con C y caída inmediata con espacio. ↓ acelera. El bloqueo tarda medio segundo y admite 15 reinicios.','SRS adjusts rotations near walls. Seven-piece bags, ghost, C hold and space hard drop are available. ↓ accelerates. Lock takes half a second with up to 15 resets.','C: ■ ↔ ▤\n   ▤\n   ⋮\n   ▱'),
 guide('Puntuación moderna','Modern scoring','1/2/3/4 líneas: 100/300/500/800 × (nivel + 1). T-spin: 400/800/1200/1600 con 0–3 líneas; mini: 100/200/400 con 0–2. Difíciles consecutivos × 1,5; combos +50 por paso. Caída: +1 suave, +2 inmediata por casilla.','1/2/3/4 lines: 100/300/500/800 × (level + 1). T-spin: 400/800/1200/1600 for 0–3 lines; mini: 100/200/400 for 0–2. Back-to-back difficult clears × 1.5; combos +50 per step. Drop: +1 soft, +2 hard per cell.','■ ■\n ■■\n■ ■'),
 guide('Perfil NES NTSC','NES NTSC profile','Sin ajustes de giro, sombra, reserva o caída inmediata. Una próxima pieza. Azar con sequías posibles, no bolsa. Repetición lateral: 16 cuadros iniciales / 6 siguientes; ↓ suprime movimiento lateral. Gravedad NTSC; nivel 29 cae una casilla por cuadro.','No rotation kicks, ghost, hold or hard drop. One next piece. Randomness can cause droughts, without a bag. Horizontal repeat: 16 initial frames / 6 subsequent; ↓ suppresses horizontal movement. NTSC gravity; level 29 falls one cell per frame.','← 16f → 6f → 6f'),
 guide('Puntuación y objetivos clásicos','Classic scoring and goals','1/2/3/4 líneas: 40/100/300/1200 × (nivel + 1), más descenso manual. Infinito continúa hasta perder; líneas termina al lograr el objetivo; tiempo termina al agotar los segundos. Se reproducen las mecánicas descritas, sin emular errores, desbordamientos o código de consola.','1/2/3/4 lines: 40/100/300/1200 × (level + 1), plus manual drop. Endless runs until loss; lines ends at the target; timed ends when seconds expire. The documented mechanics are reproduced without console glitches, overflows or console-code emulation.','4 × filas → 1200 × (N+1)')
 ],summarize:s=>({score:s.score,lines:s.lines,level:s.level,seconds:Math.floor(s.elapsed)})}
];
