import { PixelSprite, suits } from '../../ui/PixelSprite';
import { useState } from 'react';
import { difficulty, labels, select, tr, type GameDefinition, type GameViewProps } from '../../core/types';
import { canRaise, cardLabel, createPoker, evaluate, pokerBot, pokerReducer, suit, type PokerState } from './engine';
import PokerWorker from './bot.worker?worker&inline';
import './poker.css';

const categoryNames=[labels('Carta alta','High card'),labels('Pareja','Pair'),labels('Doble pareja','Two pair'),labels('Trío','Three of a kind'),labels('Escalera','Straight'),labels('Color','Flush'),labels('Full','Full house'),labels('Póker','Four of a kind'),labels('Escalera de color','Straight flush')];
function Cards({cards,hidden=false}:{cards:number[];hidden?:boolean}) {return <div className="poker-cards">{cards.map((c,i)=><span key={`${i}:${c}`} style={{animationDelay:`${i*65}ms`}} className={`poker-card ${hidden?'back':suit(c)===1||suit(c)===2?'red':''}`} aria-label={hidden?'Carta oculta / Hidden card':cardLabel(c)}>{hidden?<span aria-hidden="true">+</span>:<><b>{cardLabel(c).slice(0,-1)}</b><PixelSprite sprite={suits[[3,2,1,0][suit(c)]]} palette={{k:'currentColor'}}/></>}</span>)}</div>;}
function PokerView({state:s,dispatch,locale:l,paused,config:c}:GameViewProps<PokerState>) {
  const [amount,setAmount]=useState('');const p=s.players[s.turn];const showdown=s.street==='showdown';const owed=p?Math.max(0,s.highest-p.bet):0;const min=s.highest+s.lastRaise;const pot=s.players.reduce((n,p)=>n+p.total,0);
  return <div className="poker-game">
    <div className="poker-summary"><span>{tr(l,'MANO','HAND')} {s.handNumber} · {s.street.toUpperCase()}</span><strong>{tr(l,'BOTE','POT')} {showdown?'—':pot}</strong><span>{tr(l,'CIEGAS','BLINDS')} 10 / 20</span></div>
    <div className="poker-table"><div className="poker-board"><Cards cards={s.board}/>{!s.board.length&&<p>{tr(l,'La mesa se descubre después de las apuestas.','Community cards are dealt after betting.')}</p>}</div>
      <div className="poker-seats">{s.players.map((player,i)=><section key={i} className={`poker-seat ${i===s.turn?'active':''} ${player.folded?'folded':''}`}><header>{tr(l,'Jugador','Player')} {i+1} {i===s.dealer&&<small>ⓓ</small>}</header><Cards cards={player.hole} hidden={!(showdown&&!player.folded)&&(i!==s.turn||i>=Number(c.humans||1))}/><div><strong>{player.stack}</strong> {tr(l,'fichas','chips')} · {player.folded?tr(l,'retirado','folded'):player.allIn?tr(l,'all-in','all-in'):`${tr(l,'apuesta','bet')} ${player.bet}`}</div>{showdown&&!player.folded&&s.board.length===5&&<small>{categoryNames[evaluate([...player.hole,...s.board])[0]][l]}</small>}</section>)}</div>
    </div>
    {showdown?<div className="poker-actions"><p>{s.results.map(r=>`${tr(l,'Jugador','Player')} ${r.player+1}: +${r.amount}`).join(' · ')}</p>{s.status==='playing'&&<button onClick={()=>dispatch({type:'NEXT_HAND'})} disabled={paused}>{tr(l,'Siguiente mano','Next hand')}</button>}</div>:p&&<div className="poker-actions"><strong>{tr(l,'Turno de','Turn')} {tr(l,'jugador','player')} {s.turn+1}</strong><button disabled={paused} onClick={()=>dispatch({type:'FOLD'})}>{tr(l,'Retirarse','Fold')}</button><button disabled={paused} onClick={()=>dispatch({type:'CALL'})}>{owed?`${tr(l,'Igualar','Call')} ${Math.min(owed,p.stack)}`:tr(l,'Pasar','Check')}</button><label>{tr(l,'Apuesta total','Total bet')}<input type="number" min={min} max={p.bet+p.stack} step="1" value={amount} placeholder={String(min)} onChange={e=>setAmount(e.target.value)} /></label><button disabled={paused||!canRaise(s,p)||p.stack<=owed} onClick={()=>{dispatch({type:'RAISE',amount:Number(amount)||min});setAmount('');}}>{tr(l,'Subir','Raise')}</button><button disabled={paused||(p.bet+p.stack>s.highest&&!canRaise(s,p))} onClick={()=>dispatch({type:'ALL_IN'})}>All-in {p.stack}</button><small>{tr(l,'Subida mínima a','Minimum raise to')} {min}{!canRaise(s,p)&&` · ${tr(l,'Una subida corta no reabre las apuestas.','A short raise does not reopen betting.')}`}</small></div>}
    <ol className="poker-log" aria-live="polite">{s.log.map((entry,i)=><li key={i}>{entry[l]}</li>)}</ol>
  </div>;
}
export const poker:GameDefinition<PokerState>={
  id:'poker',name:labels('Póker','Poker'),description:labels('Texas Hold’em con fichas ficticias.','Texas Hold’em with play chips.'),category:'cards',icon:'♠',version:1,
  defaults:{players:2,humans:1,difficulty:'medium'},options:[select('players','Jugadores','Players',[[2,'2','2'],[3,'3','3'],[4,'4','4'],[5,'5','5'],[6,'6','6']],2),select('humans','Humanos','Humans',[[1,'1','1'],[2,'2','2'],[3,'3','3'],[4,'4','4'],[5,'5','5'],[6,'6','6']],1),{...difficulty,visibleWhen:c=>Number(c.humans)<(c.mode==='pairs'?4:Number(c.players))}],
  create:createPoker,reducer:pokerReducer,View:PokerView,bot:async(s,c)=>{
    // Send only the acting player's hand and public information to the worker.
    const publicState=structuredClone(s);publicState.deck=[];publicState.players.forEach((p,i)=>{if(i!==s.turn)p.hole=[];});
    if(typeof Worker==='undefined')return pokerBot(publicState,c);
    return new Promise((resolve)=>{let worker:Worker;try{worker=new PokerWorker();}catch{resolve(pokerBot(publicState,c));return;}const timer=setTimeout(()=>{worker.terminate();resolve({type:'CALL'});},5000);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();resolve(e.data.action??{type:'CALL'});};worker.onerror=()=>{clearTimeout(timer);worker.terminate();resolve(pokerBot(publicState,c));};worker.postMessage({state:publicState,config:c});});
  },getTurn:s=>s.street==='showdown'?null:{player:s.turn,bot:false,hidden:true},
  guide:[{title:labels('Dos cartas, una mesa','Two cards, one board'),text:labels('Recibes dos cartas privadas. La mejor combinación de cinco entre tus dos cartas y las cinco de la mesa gana. Los otros jugadores solo ven las suyas.','Receive two private cards. Your best five-card combination from your hand and the five community cards wins. Other players only see their own cards.'),diagram:'[A♠ K♠] + [Q♠ J♠ 10♠ 2♦ 3♣] → A♠ K♠ Q♠ J♠ 10♠'},
    {title:labels('Cuatro rondas de apuestas','Four betting rounds'),text:labels('Las ciegas son 10 y 20. Puedes pasar si no debes fichas, igualar, subir o retirarte. En dos jugadores el repartidor pone la ciega pequeña y actúa primero antes del flop. Prueba pasar o igualar.','Blinds are 10 and 20. Check when nothing is owed, call, raise or fold. Heads-up, the dealer posts the small blind and acts first before the flop. Try a check or call.'),diagram:'2 privadas → FLOP (3) → TURN (+1) → RIVER (+1)',action:{type:'CALL'}},
    {title:labels('Subidas y all-in','Raises and all-in'),text:labels('La subida mínima iguala el tamaño de la última subida completa. Un all-in menor es válido, pero no permite volver a subir a quien ya actuó, salvo que las subidas acumuladas alcancen una subida completa.','A minimum raise matches the last full raise size. A smaller all-in is legal, but does not reopen raising for a player who already acted unless cumulative raises reach a full raise.')},
    {title:labels('Manos y botes secundarios','Hands and side pots'),text:labels('Orden: carta alta, pareja, doble pareja, trío, escalera, color, full, póker, escalera de color. Con all-ins de distinto tamaño, cada jugador solo puede ganar las fichas que cubrió. Los empates reparten el bote; la ficha impar va al primero a la izquierda del repartidor.','Order: high card, pair, two pair, trips, straight, flush, full house, quads, straight flush. With unequal all-ins, you can only win chips you covered. Ties split the pot; odd chips go to the first winner left of the dealer.'),diagram:'A: 100 · B: 300 · C: 300 → bote 300 (A/B/C) + bote 400 (B/C)'}],
  summarize:s=>({hands:s.handNumber,chips:s.players[0].stack}),
};
poker.getTurn=(s,c)=>s.street==='showdown'?null:{player:s.turn,bot:s.turn>=Math.min(s.players.length,Number(c.humans)||1),hidden:true};
