// Original factual questions, authored for Timeout. Dataset license: CC BY-SA 4.0.
export const spanishQuestions: [number, string, string][] = [
  [0, "¿Cuál es la capital de Australia?", "Canberra"],
  [0, "¿En qué continente está el desierto del Sahara?", "África"],
  [0, "¿Qué océano separa América de Europa?", "Atlántico"],
  [0, "¿Qué país tiene forma de bota?", "Italia"],
  [0, "¿Cuál es la capital de Japón?", "Tokio"],
  [0, "¿Qué cordillera separa España y Francia?", "Los Pirineos"],
  [0, "¿Cuál es la capital de Canadá?", "Ottawa"],
  [0, "¿En qué país está la ciudad de Marrakech?", "Marruecos"],
  [0, "¿Cuál es la capital de Portugal?", "Lisboa"],
  [0, "¿Qué océano está al este de Australia?", "Pacífico"],
  [1, "¿En qué año llegó la expedición de Colón a América?", "1492"],
  [1, "¿Qué civilización construyó las pirámides de Guiza?", "La egipcia"],
  [1, "¿Quién fue el primer ser humano en pisar la Luna?", "Neil Armstrong"],
  [1, "¿En qué año cayó el Muro de Berlín?", "1989"],
  [1, "¿Qué ciudad quedó sepultada por el Vesubio en el año 79?", "Pompeya"],
  [
    1,
    "¿Quién fue el primer presidente de Estados Unidos?",
    "George Washington",
  ],
  [1, "¿En qué año comenzó la Primera Guerra Mundial?", "1914"],
  [1, "¿Qué imperio tuvo su capital en Constantinopla?", "El bizantino"],
  [
    1,
    "¿Qué navegante dio nombre al estrecho al sur de Sudamérica?",
    "Fernando de Magallanes",
  ],
  [1, "¿Qué pueblo desarrolló la escritura cuneiforme?", "Los sumerios"],
  [2, "¿Cuál es el símbolo químico del oro?", "Au"],
  [2, "¿Cuántos huesos tiene habitualmente el esqueleto de un adulto?", "206"],
  [2, "¿Qué planeta es el más grande del sistema solar?", "Júpiter"],
  [
    2,
    "¿Cómo se llama el proceso por el que las plantas usan la luz para producir alimento?",
    "Fotosíntesis",
  ],
  [2, "¿Cuál es la unidad del Sistema Internacional para la fuerza?", "Newton"],
  [
    2,
    "¿Qué gas absorben las plantas durante la fotosíntesis?",
    "Dióxido de carbono",
  ],
  [2, "¿Cuántos lados tiene un hexágono?", "Seis"],
  [2, "¿Qué órgano bombea la sangre?", "El corazón"],
  [2, "¿Cuál es el planeta más cercano al Sol?", "Mercurio"],
  [2, "¿Cómo se llama el cambio de líquido a gas?", "Vaporización"],
  [3, "¿Quién escribió Don Quijote de la Mancha?", "Miguel de Cervantes"],
  [3, "¿Quién pintó Las meninas?", "Diego Velázquez"],
  [
    3,
    "¿Qué compositor escribió la Novena Sinfonía con el Himno a la alegría?",
    "Ludwig van Beethoven",
  ],
  [3, "¿Quién escribió Cien años de soledad?", "Gabriel García Márquez"],
  [3, "¿Qué pintor creó el Guernica?", "Pablo Picasso"],
  [3, "¿Qué instrumento musical tiene teclas, macillos y cuerdas?", "El piano"],
  [3, "¿Quién escribió Romeo y Julieta?", "William Shakespeare"],
  [3, "¿Quién pintó La noche estrellada?", "Vincent van Gogh"],
  [3, "¿Qué poeta escribió Romancero gitano?", "Federico García Lorca"],
  [
    3,
    "¿Qué instrumento utiliza habitualmente seis cuerdas y trastes?",
    "La guitarra",
  ],
  [4, "¿Cómo se llama el vaquero protagonista de Toy Story?", "Woody"],
  [
    4,
    "¿Cómo se llama la orden de guardianes de la paz que utiliza la Fuerza en Star Wars?",
    "Los Jedi",
  ],
  [4, "¿Cómo se llama el hobbit que lleva el Anillo a Mordor?", "Frodo Bolsón"],
  [
    4,
    "¿Qué director dirigió Parque Jurásico, estrenada en 1993?",
    "Steven Spielberg",
  ],
  [4, "¿Cómo se llama la escuela de magia de Harry Potter?", "Hogwarts"],
  [
    4,
    "¿Qué película de Disney tiene como protagonista al león Simba?",
    "El rey león",
  ],
  [4, "¿De qué ciudad británica eran The Beatles?", "Liverpool"],
  [4, "¿Qué superhéroe tiene como identidad civil a Bruce Wayne?", "Batman"],
  [4, "¿Qué personaje de dibujos vive en una piña bajo el mar?", "Bob Esponja"],
  [4, "¿Cómo se llama el muñeco de nieve de Frozen?", "Olaf"],
  [
    5,
    "¿Cuántos jugadores de un equipo de fútbol pueden estar en el campo al comenzar un partido?",
    "Once",
  ],
  [5, "¿Qué pieza de ajedrez se mueve en forma de L?", "El caballo"],
  [5, "¿Cuántos anillos tiene el símbolo olímpico?", "Cinco"],
  [5, "¿En qué deporte se utiliza un volante?", "Bádminton"],
  [
    5,
    "¿Cuántos jugadores de un equipo de baloncesto juegan a la vez?",
    "Cinco",
  ],
  [
    5,
    "¿Qué prueba ciclista tiene como símbolo el maillot amarillo?",
    "El Tour de Francia",
  ],
  [5, "¿Cómo se llama el empate 40–40 en tenis?", "Deuce o iguales"],
  [5, "¿Cuántos metros mide una piscina olímpica larga?", "50 metros"],
  [5, "¿Cuántas casillas tiene un tablero de ajedrez?", "64"],
  [5, "¿Qué deporte combina natación, ciclismo y carrera a pie?", "Triatlón"],
];
